name: Deploy website to FTP

on:
  push:
    branches:
      - deploy

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          local-dir: ./
          server-dir: /public_html/

          exclude: |
            wp-content/**
            backup_fabi/**
            backup_old/**
            beta/**
            cgi-bin/**
            forms/**
            kalkulatorterkep/**
            mandatumkalkulator/**
            mediairanytu/**
            szemelynek_szolo_szavazat/**
            yourls/**
            .env


